### 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written Python code that provides functionalities to perform various tasks. These libraries contain modules and functions that can be imported into your Python scripts or programs, allowing you to leverage existing code to solve problems efficiently without having to reinvent the wheel.

We use Python libraries for several reasons:

1. **Code Reusability:** Libraries encapsulate reusable code components that can be used across different projects, saving time and effort in writing new code from scratch.

2. **Efficiency:** Python libraries often contain optimized algorithms and data structures, allowing developers to perform complex tasks efficiently without having to implement them manually.

3. **Functionality:** Libraries extend the capabilities of Python by providing specialized functions and modules for specific tasks such as data analysis, web development, machine learning, scientific computing, etc.

4. **Community Support:** Python has a large and active community that develops and maintains numerous libraries. These libraries are often well-documented and supported by the community, providing resources and assistance to developers.

Overall, Python libraries enhance productivity, enable code reuse, and empower developers to build powerful applications by leveraging existing solutions and functionalities.

### 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several differences in terms of functionality, performance, and usage:

1. **Data Type and Homogeneity:**
   - NumPy arrays are homogeneous, meaning that all elements in the array must be of the same data type. This allows for more efficient storage and computation.
   - Python lists can contain elements of different data types, providing more flexibility but potentially sacrificing performance for certain operations.

2. **Memory Efficiency:**
   - NumPy arrays are more memory efficient compared to Python lists, especially when dealing with large datasets. This is because NumPy arrays store data in a contiguous block of memory, while Python lists store references to objects, which can lead to more memory overhead.
   
3. **Performance:**
   - NumPy arrays generally offer better performance for numerical operations and mathematical computations compared to Python lists. This is due to NumPy's ability to perform vectorized operations, which are optimized and executed at the C level.
   
4. **Functionality and Operations:**
   - NumPy arrays support a wide range of mathematical operations and array manipulations, such as element-wise arithmetic operations, linear algebra operations, slicing, reshaping, and broadcasting.
   - Python lists offer more flexibility in terms of general-purpose data manipulation and support a variety of built-in methods and operations.

5. **Indexing and Slicing:**
   - Both NumPy arrays and Python lists support indexing and slicing operations. However, NumPy arrays offer more advanced indexing techniques, such as boolean indexing and fancy indexing, which allow for more expressive and efficient data selection.

In summary, while Python lists provide flexibility and ease of use for general-purpose programming, NumPy arrays are optimized for numerical computations and offer superior performance and memory efficiency for tasks involving large datasets and numerical operations.

In [1]:
'''3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Find the shape of the array
shape = array.shape

# Find the size of the array
size = array.size

# Find the number of dimensions of the array
dimensions = array.ndim

print("Array Shape:", shape)
print("Array Size:", size)
print("Array Dimension:", dimensions)


Array Shape: (3, 4)
Array Size: 12
Array Dimension: 2


In [2]:
'''4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the first row
first_row = array[0]

print("First Row of the Array:", first_row)


First Row of the Array: [1 2 3 4]


In [3]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the element at the third row (index 2) and fourth column (index 3)
element = array[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [4]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract odd-indexed elements
odd_indexed_elements = array[:, 1::2].flatten()

print("Odd-indexed elements:", odd_indexed_elements)


Odd-indexed elements: [ 2  4  6  8 10 12]


In [5]:
'''7. How can you generate a random 3x3 matrix with values between 0 and 1?'''

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.random((3, 3))

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)

Random 3x3 matrix with values between 0 and 1:
[[0.63125183 0.01623426 0.87764362]
 [0.26765974 0.04108609 0.13636787]
 [0.03090199 0.88114435 0.10820247]]


In [8]:
"""8. Describe the difference between np.random.rand and np.random.randn?'''
`np.random.rand` and `np.random.randn` are both functions provided by NumPy's random module for generating random numbers, but they differ in how they generate these numbers:"""

'''1. **`np.random.rand`:**
   - `np.random.rand` generates random numbers from a uniform distribution over the range [0, 1).
   - You specify the shape of the output array as separate arguments (not as a tuple).
   - Each value in the array is generated independently of the others.
   - This function is useful when you need random numbers from a uniform distribution.

2. **`np.random.randn`:**
   - `np.random.randn` generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
   - You specify the shape of the output array using a tuple.
   - The random numbers generated follow a standard normal distribution, which means they are centered around 0 with a standard deviation of 1.
   - This function is useful when you need random numbers from a normal distribution, which is a common requirement in statistical modeling and simulations.

In summary, `np.random.rand` generates random numbers from a uniform distribution over [0, 1), while `np.random.randn` generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.'''

'1. **`np.random.rand`:**\n   - `np.random.rand` generates random numbers from a uniform distribution over the range [0, 1).\n   - You specify the shape of the output array as separate arguments (not as a tuple).\n   - Each value in the array is generated independently of the others.\n   - This function is useful when you need random numbers from a uniform distribution.\n\n2. **`np.random.randn`:**\n   - `np.random.randn` generates random numbers from a standard normal distribution (mean=0, standard deviation=1).\n   - You specify the shape of the output array using a tuple.\n   - The random numbers generated follow a standard normal distribution, which means they are centered around 0 with a standard deviation of 1.\n   - This function is useful when you need random numbers from a normal distribution, which is a common requirement in statistical modeling and simulations.\n\nIn summary, `np.random.rand` generates random numbers from a uniform distribution over [0, 1), while `np.random.

In [6]:
'''9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

original_array = np.array([[1, 2, 3, 4],
                            [5, 6, 7, 8],
                            [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_array = np.expand_dims(original_array, axis=0)

print("Original Array:")
print(original_array)
print("\nExpanded Array:")
print(expanded_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [9]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array using np.transpose()
transposed_array = np.transpose(array)

# Alternatively, you can use the .T attribute
# transposed_array = array.T

print("Original Array:")
print(array)
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [10]:
'''11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]'''

'''Perform the following operation using Python
1. Index wise multiplication
2. Matix multiplication
3. Add both matices
4. Subtact matrix B from matrix A
5. Divide Matrix B by A
'''

import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index-wise multiplication
index_wise_multiplication = A * B
print("1. Index-wise Multiplication:")
print(index_wise_multiplication)

# 2. Matrix multiplication
matrix_multiplication = np.matmul(A, B.transpose())  # Assuming you meant matrix multiplication
print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

# 3. Add both matrices
matrix_addition = A + B
print("\n3. Matrix Addition:")
print(matrix_addition)

# 4. Subtract matrix B from matrix A
matrix_subtraction = A - B
print("\n4. Matrix Subtraction:")
print(matrix_subtraction)

# 5. Divide Matrix B by A
matrix_division = np.divide(B, A)
print("\n5. Element-wise Division of B by A:")
print(matrix_division)


1. Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Element-wise Division of B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the `byteswap()` function to swap the byte order of an array. This function swaps the byte order of the elements in the array in place. It can be useful when dealing with data stored in binary files or when working with data that is stored in a different byte order than what your system expects.

Here's how you can use `byteswap()`:

```python
import numpy as np

# Create an array with a specific byte order
array = np.array([1, 2, 3, 4], dtype=np.int32)  # Example array

# Swap the byte order of the array
array_swapped = array.byteswap()

print("Original Array:", array)
print("Array with Swapped Byte Order:", array_swapped)
```

This function swaps the byte order of the array elements in place and returns a new array with the swapped byte order. If the byte order of the array is already in the native byte order of the system, `byteswap()` does nothing.

### 13. What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function in NumPy is used to compute the inverse of a square matrix. The significance of computing the inverse of a matrix lies in various mathematical and computational applications, particularly in linear algebra and numerical computations. Here's why `np.linalg.inv` is significant:

1. **Solving Linear Equations:** One of the primary applications of matrix inversion is solving systems of linear equations. Given a matrix equation \( Ax = B \), where \( A \) is a square matrix of coefficients, \( x \) is the vector of variables, and \( B \) is the constant vector, you can solve for \( x \) by computing the inverse of \( A \) and multiplying it by \( B \), i.e., \( x = A^{-1}B \).

2. **Computing Determinants:** In many cases, computing the inverse of a matrix involves calculating its determinant. The determinant of a matrix provides information about the matrix's properties, such as its singularity (non-invertibility) or rank.

3. **Applications in Statistics and Optimization:** In statistics and optimization problems, matrix inversion is often used in techniques like linear regression, least squares estimation, and maximum likelihood estimation.

4. **Numerical Stability:** While matrix inversion provides an analytical solution to linear systems, in numerical computations, it's crucial to consider the numerical stability of the solution. Inverse matrices may not exist for singular matrices, and even if they do, computational errors can arise due to precision issues.

5. **Matrix Algebra and Transformations:** Matrix inversion plays a significant role in matrix algebra, where it facilitates transformations, such as rotation, scaling, and reflection, by allowing the transformation to be undone.

However, it's important to note that not all matrices have inverses. A matrix must be square and non-singular (i.e., its determinant must be non-zero) to have an inverse. In practice, you should also consider alternative methods, such as using matrix decompositions like LU decomposition or QR decomposition, for solving linear systems when applicable, as they can be more numerically stable and efficient than direct matrix inversion.

In [12]:
'''14. What does the np.reshape function do, and how is it used?'''

'''

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array into a new shape while preserving the total number of elements. The function returns a new array with the specified shape.

Here's how np.reshape is used:


'''

# Create a 1D array with 12 elements
arr = np.arange(12)
print("Original Array:")
print(arr)
# Output:
# [ 0  1  2  3  4  5  6  7  8  9 10 11]

# Reshape the array into a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))
print("\nReshaped Array:")
print(reshaped_arr)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Reshape the array into a 2x6 matrix
reshaped_arr_2 = np.reshape(arr, (2, 6))
print("\nReshaped Array (2x6):")
print(reshaped_arr_2)
# Output:
# [[ 0  1  2  3  4  5]
#  [ 6  7  8  9 10 11]]

# Reshape the array into a 2D array with a single column
reshaped_arr_3 = np.reshape(arr, (-1, 1))
print("\nReshaped Array (Single Column):")
print(reshaped_arr_3)
# Output:
# [[ 0]
#  [ 1]
#  [ 2]
#  [ 3]
#  [ 4]
#  [ 5]
#  [ 6]
#  [ 7]
#  [ 8]
#  [ 9]
#  [10]
#  [11]]

'''

In the examples above:

We first create a 1D array arr with 12 elements using np.arange(12).
We then reshape arr into different shapes using np.reshape. In the first case, we reshape it into a 3x4 matrix, in the second case, into a 2x6 matrix, and in the third case, into a 2D array with a single column.
When reshaping, you can specify the new shape as a tuple. One of the dimensions can be -1, which means NumPy will automatically determine the size of that dimension based on the total number of elements in the array and the other specified dimensions.
It's important to note that the reshaped array must have the same number of elements as the original array. Otherwise, NumPy will raise a ValueError.


'''



Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped Array (2x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped Array (Single Column):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


"\n\nIn the examples above:\n\nWe first create a 1D array arr with 12 elements using np.arange(12).\nWe then reshape arr into different shapes using np.reshape. In the first case, we reshape it into a 3x4 matrix, in the second case, into a 2x6 matrix, and in the third case, into a 2D array with a single column.\nWhen reshaping, you can specify the new shape as a tuple. One of the dimensions can be -1, which means NumPy will automatically determine the size of that dimension based on the total number of elements in the array and the other specified dimensions.\nIt's important to note that the reshaped array must have the same number of elements as the original array. Otherwise, NumPy will raise a ValueError.\n\n\n"

In [14]:
'''15. What is broadcasting in Numpy?'''


'''Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic operations, even if their shapes do not match exactly. Broadcasting makes it possible to perform element-wise operations between arrays of different shapes without explicitly reshaping or copying the data.

The broadcasting rule in NumPy states that the arrays in an operation can be broadcast together if their shapes are compatible. Two dimensions are compatible when they are equal, or one of them is 1. The broadcasting process then automatically stretches or duplicates the arrays along the appropriate dimensions to make their shapes compatible for the operation.

Here's a simple example to illustrate broadcasting:'''


import numpy as np

# Create a 2x3 array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1x3 array
B = np.array([10, 20, 30])

# Perform element-wise addition using broadcasting
C = A + B

print(C)


'''In this example, even though the shapes of arrays A and B are different (A is 2x3 and B is 1x3), NumPy automatically broadcasts array B to the shape of A by duplicating its elements along the first dimension. Then, it performs element-wise addition between the two arrays, resulting in array C.

Broadcasting simplifies many operations and makes code more concise and readable. It's widely used in NumPy for arithmetic operations, comparisons, and other element-wise operations between arrays of different shapes. However, it's important to understand how broadcasting works to avoid unintended behavior and ensure the correctness of your computations.'''

[[11 22 33]
 [14 25 36]]


"In this example, even though the shapes of arrays A and B are different (A is 2x3 and B is 1x3), NumPy automatically broadcasts array B to the shape of A by duplicating its elements along the first dimension. Then, it performs element-wise addition between the two arrays, resulting in array C.\n\nBroadcasting simplifies many operations and makes code more concise and readable. It's widely used in NumPy for arithmetic operations, comparisons, and other element-wise operations between arrays of different shapes. However, it's important to understand how broadcasting works to avoid unintended behavior and ensure the correctness of your computations."